on:
  workflow_call:
    inputs:
      cluster_name:
        required: true
        type: string
      namespace:
        required: true
        type: string
      deployment_name:
        required: true
        type: string
      container_name:
        required: true
        type: string
      image_url:
        required: true
        type: string
      aws_region:
        required: false
        default: ap-northeast-2
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  deploy-eks-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ inputs.aws_region }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ inputs.aws_region }} --name ${{ inputs.cluster_name }}

      - name: Image Update (Auto Restart)
        run: |
            kubectl set image -n ${{ inputs.namespace }} deployment/${{ inputs.deployment_name }} ${{ inputs.container_name }}=${{ inputs.image_url }}