name: Upload File to AWS S3
description: 파일을 AWS S3에 업로드하는 작업

inputs:
  upload_file_path:
    required: true
    description: 업로드할 파일의 경로
  aws_region:
    required: true
    description: 업로드할 S3의 region
  s3_bucket:
    required: true
    description: S3 버킷명
  s3_upload_path:
    required: true
    description: 버킷 제외한 S3 업로드 폴더 경로

runs:
  using: "composite"
  steps:
    - name: Upload to S3 (Not Windows)
      if: runner.os != 'Windows'
      run: |
        SRC="${{ inputs.upload_file_path }}"
        RECURSIVE=""
        [[ "$SRC" == */ ]] && RECURSIVE="--recursive"
        aws s3 cp "$SRC" "s3://${{ inputs.s3_bucket }}/${{ inputs.s3_upload_path }}" --region "${{ inputs.aws_region }}" $RECURSIVE
      shell: bash

    - name: Upload to S3 (Windows)
      if: runner.os == 'Windows'
      run: |
        $src = "${{ inputs.upload_file_path }}"
        $recursive = if ($src.EndsWith('/') -or $src.EndsWith('\')) { '--recursive' } else { '' }
        aws s3 cp $src "s3://${{ inputs.s3_bucket }}/${{ inputs.s3_upload_path }}" --region "${{ inputs.aws_region }}" $recursive
      shell: powershell