name: Notify Result by Discord
description: workflow 수행 결과를 Discord 채널에 전송

inputs:
  failed_jobs:
    required: true
    description: 실패한 job 내역.(ex. job1,job2)
  title:
    required: true
    description: 완료/실패에 대한 제목
  discord_webhook_url:
    required: true
    description: Discord 웹훅 url
  version:
    required: false
    description: 배포한 버전
  notify_success:
    required: false
    default: "true"
    description: 성공한 내역 알림 보낼지 여부

runs:
  using: "composite"
  steps:
    - name: Create Message
      id: create-message
      run: |
        github_url="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        message=""

        if [[ "${{ inputs.failed_jobs }}" != "" ]]; then
          jobs="${{ inputs.failed_jobs }}"
          formatted_jobs=""
          IFS=',' read -ra JOB_ARRAY <<< "$jobs"
          for job in "${JOB_ARRAY[@]}"; do
            formatted_jobs+="  - $job\n"
          done

          message="**[😢 배포 실패]**\n"
          message+="- 서비스: \`${{ inputs.title }}\`\n"
          message+="- 실패한 job:\n$formatted_jobs"
          message+="👉 [workflow 확인]($github_url)"
        elif [[ "${{ inputs.notify_success }}" == "true" ]]; then
          message="**[🐣 배포 성공]**\n"
          message+="- 서비스: \`${{ inputs.title }}\`\n"
          if [[ -n "${{ inputs.version }}" ]]; then
            message+="- 버전: \`${{ inputs.version }}\`\n"
          fi
        fi

        echo "message<<EOF" >> $GITHUB_OUTPUT
        echo -e "$message" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
      shell: bash

    - name: Send message
      if: ${{ steps.create-message.outputs.message != '' }}
      env:
        RAW_MESSAGE: ${{ steps.create-message.outputs.message }}
        DISCORD_WEBHOOK_URL: ${{ inputs.discord_webhook_url }}
      run: |
        message=$(echo "$RAW_MESSAGE" | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')
        curl -H "Content-Type: application/json" \
             -X POST \
             -d "{\"content\": \"$message\"}" \
             "$DISCORD_WEBHOOK_URL"
      shell: bash
      