name: Deploy Unity Multiplay Hosting With AWS S3
description: Unity UGS Multiplay Hosting의 Build를 업데이트하는 작업

inputs:
  ugs_project_id:
    required: true
    description: UGS의 Project ID
  ugs_env:
    required: true
    description: UGS의 Environment
  ugs_cli_service_key_id:
    required: true
    description: UGS CLI에서 사용할 Service Account의 Service Key Id
  ugs_cli_service_secret_key:
    required: true
    description: UGS CLI에서 사용할 Service Account의 Service Secret Key
  build_id:
    required: true
    description: UGS Multiplay Hosting Build의 ID
  build_version:
    required: true
    description: 빌드 버전
  s3_bucket:
    required: true
    description: S3 버킷명
  s3_upload_path:
    required: true
    description: 버킷 제외한 S3 업로드 폴더 경로
  aws_access_key_id:
    required: true
    description: S3 버킷 접근 가능한 AWS Access Key Id
  aws_secret_access_key:
    required: true
    description: S3 버킷 접근 가능한 AWS Secret Access Key

runs:
  using: "composite"
  steps:
    - name: Install UGS CLI
      # run: |
      #   curl -s https://services.docs.unity.com/ugs-cli/install.sh
      # shell: bash
      run: |
        curl -sLo ugs_installer https://ugscli.unity.com/v1 \
          && shasum -c <<<"3bbc507d4776a20d5feb4958be2ab7d4edcea8eb  ugs_installer" \
          && bash ugs_installer
      shell: bash

    - name: Update Multiplay Hosting Build
      env:
        UGS_CLI_PROJECT_ID: ${{ inputs.ugs_project_id }}
        UGS_CLI_ENVIRONMENT_NAME: ${{ inputs.ugs_env }}
        UGS_CLI_SERVICE_KEY_ID: ${{ inputs.ugs_cli_service_key_id }}
        UGS_CLI_SERVICE_SECRET_KEY: ${{ inputs.ugs_cli_service_secret_key }}
        BUCKET_S3_URI: s3://${{ inputs.s3_bucket }}/${{ inputs.s3_upload_path }}
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
      # run: |
      #   ugs multiplay-hosting build create-version "${{ inputs.build_id }}" \
      #     --project-id "${{ inputs.ugs_project_id }}" \
      #     --environment-name "${{ inputs.ugs_env }}" \
      #     --bucket-url "${BUCKET_S3_URI}" \
      #     --build-version-name "${{ inputs.build_version }}"
      run: |
        ugs --version
        ugs config set project-id "${UGS_CLI_PROJECT_ID}"
        ugs config set environment-name "${UGS_CLI_ENVIRONMENT_NAME}"
        ugs status
        # ugs env list
        ugs game-server-hosting build create-version "${{ inputs.build_id }}" \
          --bucket-url "${BUCKET_S3_URI}" \
          --build-version-name "${{ inputs.build_version }}" \
          --access-key "${AWS_ACCESS_KEY_ID}" \
          --secret-key "${AWS_SECRET_ACCESS_KEY}"
      shell: bash