name: Build Maui iOS Platform And Upload to AWS S3

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      work_dir:
        required: true
        type: string
      project_name:
        required: true
        type: string
      target_framework:
        required: true
        type: string
      dotnet_version:
        required: true
        type: string
      artifact_name:
        required: true
        type: string
      codesign_key:
        required: true
        type: string
      codesign_provision:
        required: true
        type: string
      version:
        required: true
        type: string
      ios_display_version_name:
        required: true
        type: string
      runtime_identifier:
        required: false
        default: ios-arm64
        type: string
      publish_dir:
        required: false
        default: publish
        type: string
      build_configuration:
        required: false
        default: Release
        type: string
    secrets:
      GIT_BOT_TOKEN:
        required: true
      IOS_CERT_BASE64:
        required: true
      IOS_CERT_PASSWORD:
        required: true
      IOS_PROVISIONING_BASE64:
        required: true

jobs:
  build-and-upload-maui-ios-aws-s3:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      
      - name: Install Apple Certificate
        env:
          P12_DISTRIBUTION_CERTIFICATE_BASE64: ${{ secrets.IOS_CERT_BASE64 }}
          P12_DISTRIBUTION_CERTIFICATE_PASSWORD: ${{ secrets.IOS_CERT_PASSWORD }}
        run: |
          # 인증서 파일 생성
          CERTIFICATE_PATH=$RUNNER_TEMP/distribution_certificate.p12
          echo "$P12_DISTRIBUTION_CERTIFICATE_BASE64" | base64 --decode > $CERTIFICATE_PATH
          
          # 새로운 키체인 생성 (GitHub Actions 환경에서 더 안정적)
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          KEYCHAIN_PASSWORD=actions
          
          # 키체인 생성 및 설정
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          
          # 인증서 임포트
          security import $CERTIFICATE_PATH -P "$P12_DISTRIBUTION_CERTIFICATE_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH ~/Library/Keychains/login.keychain-db
          security default-keychain -s $KEYCHAIN_PATH
          
          # 키체인 권한 설정
          security set-key-partition-list -S apple-tool:,apple: -s -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          
          # 인증서 확인
          echo "=== Installed certificates ==="
          security find-identity -v -p codesigning
  
      - name: Install provisioning profile
        run: |
          PP_PATH="$RUNNER_TEMP/profile.mobileprovision"
          echo "${{ secrets.IOS_PROVISIONING_BASE64 }}" | base64 -d > "$PP_PATH"
          
          # 프로비저닝 프로파일 UUID 추출
          PP_UUID=$(security cms -D -i "$PP_PATH" | plutil -extract UUID xml1 -o - - | xmllint --xpath "string(//string)" -)
          
          # 프로비저닝 프로파일 설치
          mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
          cp "$PP_PATH" "$HOME/Library/MobileDevice/Provisioning Profiles/$PP_UUID.mobileprovision"
          
          echo "Provisioning profile installed with UUID: $PP_UUID"

      
      - name: Checkout code from ${{ inputs.branch }}
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet_version }}

      - name: Increment Application Display Version
        id: increment-ios-display-version
        uses: Cream2025/workflow-kit/.github/actions/utils/increment-var-counter@main
        with:
          repository_var_name: ${{ inputs.ios_display_version_name }}
          github_token: ${{ secrets.GIT_BOT_TOKEN }}

      - name: Build Maui iOS Platform
        uses: Cream2025/workflow-kit/.github/actions/common/build/maui/ios@main
        with:
          work_dir: ${{ inputs.work_dir }}
          project_name: ${{ inputs.project_name }}
          target_framework: ${{ inputs.target_framework }}
          runtime_identifier: ${{ inputs.runtime_identifier }}
          artifact_name: ${{ inputs.artifact_name }}
          codesign_key: ${{ secrets.CODESIGN_KEY }}
          codesign_provision: ${{ inputs.codesign_provision }}
          version: ${{ inputs.version }}
          application_display_version: ${{ steps.increment-ios-display-version.outputs.new_value }}
          publish_dir: ${{ inputs.publish_dir }}
          build_configuration: ${{ inputs.build_configuration }}
          ios_provisioning_base64: ${{ secrets.IOS_PROVISIONING_BASE64 }}


