name: Build Maui iOS Platform And Upload to AWS S3

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      work_dir:
        required: true
        type: string
      project_name:
        required: true
        type: string
      target_framework:
        required: true
        type: string
      dotnet_version:
        required: true
        type: string
      artifact_name:
        required: true
        type: string
      codesign_key:
        required: true
        type: string
      codesign_provision:
        required: true
        type: string
      version:
        required: true
        type: string
      application_display_version:
        required: true
        type: string
      ios_cert_base64:
        required: true
        type: string
      ios_cert_password:
        required: true
        type: string
      ios_provisioning_base64:
        required: true
        type: string
      ios_display_version_name:
        required: true
        type: string
      runtime_identifier:
        required: false
        default: ios-arm64
        type: string
      publish_dir:
        required: false
        default: publish
        type: string
      build_configuration:
        required: false
        default: Release
        type: string
    secrets:
      GIT_BOT_TOKEN:
        required: true

jobs:
  build-and-upload-maui-ios-aws-s3:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code from ${{ inputs.branch }}
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet_version }}

      - name: Increment Application Display Version
        id: increment-ios-display-version
        uses: Cream2025/workflow-kit/.github/actions/util/increment-var-counter@main
        with:
          repository_var_name: ${{ inputs.ios_display_version_name }}
          github_token: ${{ secrets.GIT_BOT_TOKEN }}

      
      - name: Build Maui iOS Platform
        uses: Cream2025/workflow-kit/.github/actions/common/build/maui/ios@main
        with:
          work_dir: ${{ inputs.work_dir }}
          project_name: ${{ inputs.project_name }}
          target_framework: ${{ inputs.target_framework }}
          runtime_identifier: ${{ inputs.runtime_identifier }}
          artifact_name: ${{ inputs.artifact_name }}
          codesign_key: ${{ inputs.codesign_key }}
          codesign_provision: ${{ inputs.codesign_provision }}
          version: ${{ inputs.version }}
          application_display_version: ${{ needs.increment-ios-display-version.outputs.new_value }}
          publish_dir: ${{ inputs.publish_dir }}
          build_configuration: ${{ inputs.build_configuration }}
          ios_cert_base64: ${{ inputs.ios_cert_base64 }}
          ios_cert_password: ${{ inputs.ios_cert_password }}
          ios_provisioning_base64: ${{ inputs.ios_provisioning_base64 }}


