name: Get Version by Tag or Input

on:
  workflow_call:
    inputs:
      input_version:
        required: false
        type: string
      branch:
        required: true
        type: string
      use_timestamp:
        required: false
        description: live 이외 branch에서 patch 버전에 timestamp를 넣을지 여부
        type: boolean
        default: true
    outputs:
      version:
        description: 버전 정보(ex. v1.0.0)
        value: ${{ jobs.get-version.outputs.version }}
      simple_version:
        value: ${{ jobs.get-version.outputs.simple_version }}
        description: 간단한 버전 정보(ex. 1.0.0)

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      simple_version: ${{ steps.get-version.outputs.simple_version }}
      
    env:
      BRANCH: ${{ inputs.branch }}
      USE_TIMESTAMP: ${{ inputs.use_timestamp }}

    steps:
      - name: Set current datetime
        id: datetime
        run: echo "date=$(date +'%y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Get version and validate
        id: get-version

        env:
          EVENT_NAME: ${{ github.event_name }}
          INPUT_VERSION: ${{ github.event.inputs.version }}
          DATETIME: ${{ steps.datetime.outputs.date }}
          

        run: |
          if [[ "$EVENT_NAME" == "push" ]]; then
            TAG="${GITHUB_REF##*/}" # dev-api-v1.0.250616171415
            VERSION=$(echo "$TAG" | awk -F '-' '{print $NF}')
          else
            CURRENT_BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF##refs/heads/}}"
            if [[ "$BRANCH" != "live" && "$USE_TIMESTAMP" == "true" ]]; then
              VERSION="$INPUT_VERSION.$DATETIME"
            else
              VERSION="$INPUT_VERSION.0"
            fi

            echo "Validating branch..."
            echo "Current Branch: $CURRENT_BRANCH"
            echo "Expected Branch: $BRANCH"
            if [[ "$CURRENT_BRANCH" != "$BRANCH" ]]; then
              echo "Current branch is '$CURRENT_BRANCH'. This Workflow can be run on '$BRANCH'."
              exit 1
            fi
          fi
          
          echo "Validating version format: $VERSION"
          if [[ ! "$VERSION" =~ ^v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            echo "Error: VERSION must be 'v<숫자>.<숫자>.<숫자>' format. (ex. v1.0.250616215300)"
            exit 1
          fi

          SIMPLE_VERSION="${BASH_REMATCH[1]}"
          
          echo "VERSION: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "simple_version=$SIMPLE_VERSION" >> $GITHUB_OUTPUT