name: Get Version by Tag or Variable

on:
  workflow_call:
    inputs:
      input_version:
        required: false
        type: string
      branch:
        required: true
        type: string
    outputs:
      version:
        description: 버전 정보(ex. v1.0.0)
        value: ${{ jobs.get-version.outputs.version }}
      simple_version:
        value: ${{ jobs.get-version.outputs.simple_version }}
        description: 간단한 버전 정보(ex. 1.0.0)

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      simple_version: ${{ steps.get-version.outputs.simple_version }}
      
    env:
      BRANCH: ${{ inputs.branch }}

    steps:
      - name: Get version and validate
        id: get-version

        env:
          EVENT_NAME: ${{ github.event_name }}

        run: |
          if [[ "$EVENT_NAME" == "push" ]]; then
            TAG="${GITHUB_REF##*/}" # dev-api-v1.0.0
            VERSION=$(echo "$TAG" | awk -F '-' '{print $NF}')
          else
            CURRENT_BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF##refs/heads/}}"

            echo "Validating branch..."
            echo "Current Branch: $CURRENT_BRANCH"
            echo "Expected Branch: $BRANCH"
            if [[ "$CURRENT_BRANCH" != "$BRANCH" ]]; then
              echo "Current branch is '$CURRENT_BRANCH'. This Workflow can be run on '$BRANCH'."
              exit 1
            fi

            BRANCH_UPPER=$(echo "$BRANCH" | tr '[:lower:]' '[:upper:]')
            VERSION_VARIABLE_NAME="VERSION_${BRANCH_UPPER}"

            echo "Variable name: $VERSION_VARIABLE_NAME"

            var_json=$(curl -s -H "Authorization: Bearer ${{ secrets.GIT_BOT_TOKEN }}" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/${{ github.repository }}/actions/variables/$VERSION_VARIABLE_NAME)
              
            VERSION=$(echo "$var_json" | jq -r '.value')
          fi
          
          echo "Validating version format: $VERSION"
          if [[ ! "$VERSION" =~ ^v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            echo "Error: VERSION must be 'v<숫자>.<숫자>.<숫자>' format. (ex. v1.0.0)"
            exit 1
          fi

          SIMPLE_VERSION="${BASH_REMATCH[1]}"
          
          echo "VERSION: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "simple_version=$SIMPLE_VERSION" >> $GITHUB_OUTPUT