name: Build Web Default And Upload to AWS ECR

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      work_dir:
        required: true
        type: string
      project_name:
        required: true
        type: string
      repository_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      aws_ecr_registry:
        required: true
        type: string
      build_configuration:
        required: false
        default: Release
        type: string
      aws_region:
        required: false
        default: ap-northeast-2
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
    outputs:
      image_url:
        description: 'Docker Image URL'
        value: ${{ jobs.get-version.outputs.version }}

jobs:
  build-and-upload-web-default-aws-ecr:
    runs-on: ubuntu-latest

    env:
      IMAGE_URL: ${{ inputs.aws_ecr_registry }}/${{ inputs.repository_name }}:${{ inputs.image_tag }}

    steps:
      - name: Checkout code from ${{ inputs.branch }}
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ inputs.aws_region }}

      - name: Build Web Default
        uses: ./.github/actions/common/build/web/default
        with:
          work_dir: ${{ inputs.work_dir }}
          project_name: ${{ inputs.project_name }}
          image_url: ${{ env.IMAGE_URL }}
          build_configuration: ${{ inputs.build_configuration }}

      - name: Upload Image to AWS ECR
        uses: ./.github/actions/common/upload/aws-ecr
        with:
          work_dir: ${{ inputs.work_dir }}
          image_url: ${{ env.IMAGE_URL }}
          aws_region: ${{ inputs.aws_region }}
          ecr_registry: ${{ inputs.aws_ecr_registry }}

      - name: Set Image URL Output
        run: echo "image_url=$IMAGE_URL" >> $GITHUB_OUTPUT