name: Deploy Unity Multiplay Hosting By AWS S3

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      project_id:
        required: true
        type: string
      build_id:
        required: true
        type: string
      build_version:
        required: true
        type: string
      s3_bucket:
        required: true
        type: string
      s3_upload_path:
        required: true
        type: string

jobs:
  deploy-unity-multiplay-hosting-aws-s3:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Install UGS CLI
        run: |
          curl -sLo ugs_installer https://ugscli.unity.com/v1 \
            && shasum -c <<<"3bbc507d4776a20d5feb4958be2ab7d4edcea8eb  ugs_installer" \
            && bash ugs_installer
        shell: bash

      - name: Update Unity Multiplay Hosting Build With AWS S3
        uses: Cream2025/workflow-kit/.github/actions/common/deploy/unity-multiplay-hosting/aws-s3@main
        with:
          ugs_project_id: ${{ inputs.project_id }}
          ugs_env: ${{ inputs.branch }}
          build_id: ${{ inputs.build_id }}
          build_version: ${{ inputs.build_version }}
          s3_bucket: ${{ inputs.s3_bucket }}
          s3_upload_path: ${{ inputs.s3_upload_path }}