on:
  workflow_call:
    inputs:
      branch:
        required: true
        description: 브랜치
        type: string
    outputs:
      version:
        description: 버전 정보
        value: ${{ jobs.call-workflow.outputs.version }}

jobs:
  call-workflow:
    uses: ./.github/workflows/common/get-version/label.yml
    with:
      branch: ${{ inputs.branch }}